### ISSUE TITLE
Permanent mute

### ISSUE THREAD

**Issue by lbermud** [add-ons/screensaver.turnoff#4]
Tried the addon and it put Kodi into permanent mute.  Little red icon below the time.  Win10 pc functions normally audio working fine outside of Kodi.  No signs of audio muted within Kodi, all audio settings checked within Kodi 17.6.   Muted sound within the addon setting for screen shut off/ shutdown and permanently muted.  Not happy!

**Comment by dagwieers** [comment]
It should unmute when getting out of the screensaver. The mute/unmute is optional and configurable, but without mute/unmute, it's possible your audio-system makes noise on events (like on RPi which is never turned off).

So have you tried turning it off ?

**Comment by MCTyler** [comment]
Same Here....Even uninstalled the Power off screen saver and Kodi remains Permanently muted. All I can do is wipe the installation and re-install... Fix this if it's gonna be included in Kodi.

**Comment by dagwieers** [comment]
@MCTyler Uninstalling will make no difference to whether Kodi is muted. Usually you can turn up/down the volume to go out of mute state. But if you don't want this addon to mute your audio, don't enable that functionality in the settings.

PS If you want to get any help here, it would help if you provided any information related to your environment. Maybe there is a chance to pinpoint this to a Kodi release or a platform, who knows.

**Comment by MCTyler** [comment]
I finally fixed it with the Yatse Remote. On Fire TV and I'm sure others there is no way to access any audio functions that I'm aware of like this.

**Comment by MCTyler** [comment]
May want to add some sort of disclaimer Since Fire Device Remotes will not effect Kodi Audio.

**Comment by dagwieers** [comment]
@MCTyler Can you disable this functionality and see if that makes a difference. I guess I can disable this functionality by default, but in essence it should turn audio back on, apparently on some devices this does not work (always?).

Also by muting audio it turns A/V receivers off which saves on energy, so I would rather keep this on by default (and make it simply work everywhere out-of-the-box).

**Comment by MCTyler** [comment]
Disabling the Audio Mute works fine...Probably should be the default setting....It does not turn the Audio back on with Fire TV and Kodi Lei.

**Comment by dagwieers** [comment]
And no, I am not going to add any sort of disclaimer because this clearly is a bug and a disclaimer would indicate this bug is expected where it really is not.

If you like you can play with the python script to see what works for you (or debug why it fails). Since you can reproduce it, you should be able to figure this out quite easily and propose a fix.

I still think this is a sensible default and we should close this bug. What Kodi version? What platform? Any information?

**Update:** Our messages crossed.

**Comment by MCTyler** [comment]
Kodi Version Lei? right? Platform Fire TV.

**Comment by MCTyler** [comment]
Kodi 18.1 Compiled 2/2019

**Comment by MCTyler** [comment]
Excellent Program BTW!

**Comment by dagwieers** [comment]
Ok, looking at the code I can see a possible cause for this. The builtin to mute and unmute is named 'Mute' and [it toggles the mute functionality on Kodi](https://kodi.wiki/view/List_of_built-in_functions#Application_built-in.27s). So if Kodi for whatever reason unmutes automatically after resume we are muting it again.

So what I could try doing instead of using the Mute-toggle, is Turn volume down and up again. In fact I should be doing this before turning Mute on as well, because if it was already muted, using the Mute-builtin would unmute.

It's a crazy world where Mute is a toggle between mute and unmute...

**Comment by dagwieers** [comment]
@MCTyler Can you please test the latest branch? I think I nailed it if I have the cause right.
See: https://github.com/dagwieers/screensaver.turnoff/commit/4fe0e1e35682895c0a6158b7f7a80a923164baba

**Comment by MCTyler** [comment]
Hmmm...not a programmer.... how would I add this to my latest Kodi Build?

**Comment by MCTyler** [comment]
0.9.1 ? I added it and allowed it to mute and when I resumed its stuck in mute with all the functions I have access to on the Fire-TV Remote. :(

**Comment by MCTyler** [comment]
Ahh I see...how long will this take to propagate to Kodi?  v0.10.0

**Comment by dagwieers** [comment]
So the real issue was that the unmute was called twice in some occasions which results in it being toggled one more time. The new implementation uses JSON-RPC to set it to mute or unmute (no longer toggles) which avoided the issue. But the code logic has been improved and it should not be called more than once now.

So the current code should work fine. It only propagates to Kodi if I report the new version. But I'd like to fix the LogOff issue on v18 first.

**Comment by dagwieers** [comment]
I also have 2 new features, to more easily enable this screensaver from the screensaver's settings page, as well as testing the screensaver from the settings. However, this second function also does not work correctly. It seems the Kodi interface has quite some quirks :-/
